### PR TITLE
refactored to functional components from class

### PR DESCRIPTION
**Pull request by sherwinmina**
Hey guys,

I spoke to Max yesterday on refactoring some of the react Class components into functional components. There's definitely a lot of opportunity to change  all the components that only renders a view and doesn't need a life cycle method into a functional component. 

Best,
Sherwin

### CODE REVIEW

**Comment by MaxWofford** [comment]
Awesome! Thanks @sherwinmina. I'll get this reviewed by EOD.

**Comment by MaxWofford** [comment]
@sherwinmina: Looks like there's a change to the repo's submodules in this PR:

screenshot_2017-09-22_15 19 07

Can you run this to update your submodules? Then amend the commit so it doesn't show up in the history.

```git
git submodule init
git submodule update
```

**Comment by sherwinmina** [comment]
Hey Max, 

Thanks for the review. Let me know if this works.

**Comment by MaxWofford** [comment]
Just moved it to #206 so I could make some quick changes to indentation.

**Pull request closed without merging**
