### PR TITLE
Fix streak syncing

### PR DESCRIPTION
**Pull request by paked**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@paked Could you fix the tests?

**Comment by paked** [comment]
Tests are fine.


Looks like something is wrong with git submodules?

Geh...

On 14 Jul. 2017 17:14, "Max Wofford" <notifications@github.com> wrote:

@paked <https://github.com/paked> Could you fix the tests?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hackclub/monolith/pull/40#issuecomment-315495182>, or mute
the thread

**Comment by MaxWofford** [comment]
@zachlatta ^

**Comment by zachlatta** [comment]
On it now.

**Comment by zachlatta** [comment]
This doesn't have anything to do with `./bin/deploy`. CircleCI is running `git submodule update --depth 1`, which fails. If it runs `git submodule update` instead, it doesn't fail.

I'd update `circle.yml` to have it run the latter to fix this.

**Comment by MaxWofford** [comment]
Just submitted a PR for that @zachlatta. @paked: Could I get some context on this PR? When would an application's interesting project be nil?

**Comment by paked** [comment]
I opened this PR because I thought I knew why Streak syncing wasn't working, turns out I was wrong. This line breaking is very much expected behaviour.

As pointed out by @MaxWofford above, there is never a case where the interesting project is not set. The actual way to fix Streak syncing is to wait for the Club Application migration to finish.

**Pull request closed without merging**
