### PR TITLE
Fix Hackbot (aka Orpheus) grammar, closes #170

### LINKED ISSUE #170: Hackbot accountability using incorrect grammar
Currently:
```
There are 1 applications that have been around for like two days... and STILL haven't been reviewed
1 clubs have been accepted, but haven't had their onboarding calls schedule after a week!
```
Expected:
```
There is 1 application that has been around for like two days... and STILL hasn't been reviewed
1 club has been accepted, but hasn't had their onboarding call schedule after a week!
```

### PR DESCRIPTION
**Pull request by ifvictr**
Orpheus will now speak grammatically correct English! :tada:

### CODE REVIEW

**Comment by MaxWofford** [comment]
I think this can be done with https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize

**Comment by ifvictr** [comment]
How would one use that? I want to use this as an opportunity to start learning Ruby.

**Comment by MaxWofford** [comment]
@ifvictr: the link I sent wasn't a great way to get started. https://apidock.com/rails/String/pluralize might be better. If you've got specific questions about how to use it after looking at the new link then don't hesitate to ask!

**Comment by MaxWofford** [comment]
Assigning myself to this b/c @paked is staying with family right now

@ifvictr: just ping me once it's ready to be reviewed

**Comment by ifvictr** [comment]
@MaxWofford I saw that you reverted #258. Is this fix going to be considered (even as a temp)?

**Comment by MaxWofford** [comment]
@ifvictr happy to. just open it up and tell me when it's ready to test

**Comment by ifvictr** [comment]
@MaxWofford Yeah, GitHub won't let me reopen this PR. It should work.

**Comment by MaxWofford** [comment]
Looks like you deleted your fork of the repo, which is preventing the PR from being reopened. Can you create a new PR?

**Comment by ifvictr** [comment]
Sorry for the delay. I opened a new PR at #270.

**Pull request closed without merging**
