### PR TITLE
Get rid of the legacy web/ project

### PR DESCRIPTION
**Pull request by zachlatta**
WIP.

### CODE REVIEW

**Comment by MaxWofford** [comment]
Heads up that this removes https://hackclub.com/hackbot/teams/new. We won't have a way to set up new dev environments for Orpheus. @lachlanjc @zachlatta

**Comment by zachlatta** [comment]
@MaxWofford: yeah... was thinking about that. How bad do you think it'd be to just manually make the POST requests to set up the bot? I figure we can improve the flow at some point in the near future.

**Comment by lachlanjc** [comment]
Was not aware of that page. If something’s definitely needed, add a to-do and I can make it next week. But in support of this PR  👍

**Comment by zachlatta** [comment]
Going for it!

**Pull request merged**
